version: "3"
services:
  alfresco:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: willypp/alfresco
    ports:
      - "7848:3389"
      - "7849:22"
      - "7850:8444"
    environment:
      - PASSWORD
      - TZ
    volumes:
      - ~/ccalfresco2:/home/willd
    env_file:
      - .env