apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
spec:
  type: LoadBalancer
  selector:
    instance: {{ .Release.Name }}
  ports:
    - name: rdp
      protocol: TCP
      port: 3389
      targetPort: 3389
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: kasmvnc
      protocol: TCP
      port: 8444
      targetPort: 8444
