apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-lb
  replicas: 1
  selector:
    matchLabels:
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        instance: {{ .Release.Name }}
    spec:
      containers:
      - name: webtop
        image: ghcr.io/willpakpoy/alfresco
        ports:
        - containerPort: 3389
          name: rdp
        - containerPort: 22
          name: ssh
        - containerPort: 8444
          name: kasmvnc
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: PASSWORD
        volumeMounts:
        - name: home
          mountPath: /home/willd
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      storageClassName: nfs
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
