apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        instance: {{ .Release.Name }}
    spec:
      containers:
      - name: webtop
        image: ghcr.io/willpakpoy/alfresco
        # set the pgdata to /pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: home
          mountPath: /home/willd
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi