version: "3"
services:
  alfresco:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: radfordhmdt.azurecr.io/alfresco-emergency-lol
    ports:
      - "7848:3389"
      - "7849:22"
      - "7850:8444"
    environment:
      - PASSWORD
      - TZ
    volumes:
      - ~/ccalfresco23:/home/willd
    env_file:
      - .env
